import { Inter } from "next/font/google";
import "./globals.css";

import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gamified",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const headersList = headers();
  const fullUrl = headersList.get("x-full-url");

  const authPaths = ["/dashboard", "/tutorial", "/login"];
  const isAuthPath = authPaths.some((path) => fullUrl?.includes(path));

  console.log("Full URL:", fullUrl);

  return (
    <html lang="en">
      <body
        className={`${inter.className} ${
          isAuthPath ? "dashboard_body" : " bg_body"
        } relative bg-brand-black`}
      >
        <main className="w-full h-full relative">{children}</main>
      </body>
    </html>
  );
}
