import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/views/shared/layout/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gamified",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} antialiased bg-brand-black`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
