import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/views/shared/layout/header";
import Image from "next/image";
import BackgroundImage from "@/app/images/owinr-background.png";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gamified",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} relative bg-brand-black`}>
        <Image
          src={BackgroundImage}
          fill
          alt='logo'
          className='object-cover '
        />
        <main className='w-full h-full relative'>
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
